name: Auto Build Test

on:
  push:
    branches: [ "bepinex5" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # 必须开启，否则无法创建 Release
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - name: Build
      run: dotnet build --configuration Release

    # 使用 Python 快速生成一个时间戳 Tag，避免冲突
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "DLL-${{ github.run_number }}" # 使用运行次数作为标签，永不重复
        files: |
          **/*.dll
          !**/obj/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
