name: Auto Build Test

on:
  push:
    branches: [ "bepinex5" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - name: Build
      run: dotnet build --configuration Release

    # 重点：这一步会把 dll 变成 Release 里的文件，直接点击下载
    - name: Auto Release DLL
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: |
          **/*.dll
          !**/obj/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
